# Generated by Django 6.0.1 on 2026-01-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('relapse', 'relapse')], max_length=20),
        ),
    ]
